services:
  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-finance_tracker}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${MYSQL_USER:-financeuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-financepassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # # FastAPI Backend - Development Mode
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-financeuser}:${MYSQL_PASSWORD:-financepassword}@db/finance_tracker
  #     - JWT_SECRET=${JWT_SECRET:-your-super-secret-key-change-this-in-production}
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # Next.js Frontend - Development Mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER:-financeuser}
      - DB_PASSWORD=${MYSQL_PASSWORD:-financepassword}
      - DB_NAME=${MYSQL_DATABASE:-finance_tracker}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-key-change-this-in-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - ./frontend:/app
    # depends_on:
    #   - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 